### ISSUE TITLE
A spinning circle under `Pinned`

### ISSUE THREAD

**Issue by tianheg** [antfu/github-doorcat#22]
https://user-images.githubusercontent.com/52186032/134019062-574d1f4e-d33d-4887-9629-3dcb699b89ff.mp4

The circle is annoying, can you reproduce it? It appears everyone's profile at GitHub. I'm using Google Chrome 93.0.4577.63 (Official Build) (64-bit), Arch linux. If need more info, please let me know

**Comment by Milo123459** [comment]
Reproduced, happens to me as well. Ridiculously annoying.

**Comment by exbotanical** [comment]
Reproduced as well. This is caused by an unused selector - the reference to which was briefly [added](https://github.com/antfu/github-doorcat/pull/20/commits/174306e3f4a0b580b764224cc588156fa77544bd#diff-be1682c163a64e23a705c0f671d3e6bf9e82069f656150f37533de22151cf4e8R127), then [removed](https://github.com/antfu/github-doorcat/pull/20/commits/24ae11c5191ad8edac9d5a479c9b93394c0c38e1#diff-be1682c163a64e23a705c0f671d3e6bf9e82069f656150f37533de22151cf4e8L77) in a subsequent commit.

I'll link a PR in just a minute.
